name: Generate tracks.json from Telegram

on:
  workflow_dispatch:  # Позволяет запускать скрипт вручную

jobs:
  generate:
    runs-on: ubuntu-latest  # Используем Ubuntu в качестве окружения

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Загружаем код из репозитория

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Устанавливаем нужную версию Python

      - name: Install dependencies
        run: |
          pip install telethon  # Устанавливаем библиотеку для работы с Telegram API

      - name: Generate tracks.json
        run: python scripts/generate_tracks.py  # Запускаем скрипт
        env:
          API_ID: ${{ secrets.API_ID }}  #  API ID
          API_HASH: ${{ secrets.API_HASH }}  #  API HASH
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}  # ID канала

      - name: Upload tracks.json as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tracks
          path: tracks.json  # Загружаем созданный файл как артефакт
